variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: 
  - paper
  - build
  - test

paper:
  image: ghcr.io/strau0106/latex:main
  stage: paper
  before_script: 
    - cd paper
  script: 
    - echo $CI_COMMIT_SHORT_SHA > githash.tex
    - echo $CI_COMMIT_BRANCH > gitbranch.tex
    - echo $CI_JOB_ID > jobid.tex
    - latexmk main.tex
    - latexmk main-journal.tex
  artifacts:
    paths:
      - paper/*.pdf
    expire_in: 10 weeks
  when: on_success

.verilate:
  stage: build
  image: ghcr.io/strau0106/verilator:master
  before_script: 
    - mkdir computer/build
    - cd computer/build
  script: 
    - cmake .. -G Ninja
    - ninja
  artifacts:
    untracked: true

.verilator-test:
  stage: test
  image: ghcr.io/strau0106/verilator:master
  dependencies:
    - verilate
  before_script: 
    - cd computer/build
  script:
    - export GTEST_OUTPUT="xml:reports/"
    - ctest || true
  artifacts:
    expire_in: 10 weeks
    reports:
      junit: computer/build/reports/*
    when: always

#verilator-coverage:
#  stage: test
#  image: ghcr.io/strau0106/verilator:master
#  dependencies:
#    - verilate
#  before_script: 
#    - cd computer/build
#  script:
#    - make runtest || true
#    - make coverage
#   coverage: '/Total coverage: \d+\.\d+/'
