stages: 
  - build


paper:
  image: ghcr.io/strau0106/latex:main
  stage: build
  before_script: 
    - cd paper
  script: 
    - latexmk main.tex
  artifacts:
    paths:
      - paper/*.pdf
    expire_in: 10 weeks
  when: on_success
