variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: 
  - paper
  - build
  - test

paper:
  image: ghcr.io/strau0106/latex:main
  stage: paper
  before_script: 
    - cd paper
  script: 
    - latexmk main.tex
  artifacts:
    paths:
      - paper/*.pdf
    expire_in: 10 weeks
  when: on_success

verilate:
  stage: build
  image: ghcr.io/strau0106/verilator:master
  before_script: 
    - cd computer
    - make gtest || true
  script: 
    - make
  artifacts:
    untracked: true

verilator-test:
  stage: test
  image: ghcr.io/strau0106/verilator:master
  dependencies:
    - verilate
  before_script: 
    - cd computer
  script:
    - export GTEST_OUTPUT="xml:reports/"
    - make runtest || true
  artifacts:
    expire_in: 10 weeks
    reports:
      junit: computer/reports/*
    when: always

verilator-coverage:
  stage: test
  image: ghcr.io/strau0106/verilator:master
  dependencies:
    - verilate
  before_script: 
    - cd computer
  script:
    - make runtest || true
    - 'make coverage | perl -nle "print \"Total coverage: $1\" and exit if m/Total coverage .* (\d+\.\d+)%/\"'
  coverage: '/Total coverage: \d+\.\d+/'