variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: 
  - build

paper:
  image: ghcr.io/strau0106/latex:main
  stage: build
  before_script: 
    - cd paper
  script: 
    - latexmk main.tex
  artifacts:
    paths:
      - paper/*.pdf
    expire_in: 10 weeks
  when: on_success

verilator-coverage:
  image: verilator/verilator
  stage: build
  before_script: 
    - cd computer
    - make gtest || true
  script: 
    - export GTEST_OUTPUT="xml:./report.xml"
    - make runtest || true # No interest in if all tests pass or not, thats what the html is for.
    - make genhtml
  artifacts:
    paths:
      - computer/logs/html
      - computer/report.xml
    untracked: true
    expire_in: 10 weeks
    reports:
      junit: computer/report.xml
    when: always
